# Generated by Django 4.0.5 on 2022-06-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitprofile',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Commit Status'),
        ),
    ]
